---
- name: "Prepare for new deployment on old hosts"
  hosts: retrospring
  become: yes
  roles:
    - name: legacy_prepare

- name: "Deploy Sidekiq on old host and run migrations"
  hosts: retrospring
  become: yes
  roles:
    #- name: nginx
    - name: legacy_deploy
