---
- name: "Set up Grafana Cloud agent"
  hosts: all
  become: yes
  roles:
    - name: grafanacloud

- name: "Prepare for new deployment"
  hosts: retrospringnew
  become: yes
  roles:
    - name: prepare

- name: "Prepare for new deployment on old hosts"
  hosts: retrospring
  become: yes
  roles:
    - name: legacy_prepare

- name: "Deploy Sidekiq on old host and run migrations"
  hosts: retrospring
  become: yes
  roles:
    #- name: nginx
    - name: legacy_deploy

- name: "Deploy containerised Retrospring (web instances)"
  hosts: retrospringnew_web
  serial: "50%"
  become: yes
  roles:
    - name: deploy

- name: "Deploy containerised Retrospring (sidekiq instances)"
  hosts: retrospringnew_sidekiq
  become: yes
  roles:
    - name: deploy
