---
- block:
  - name: "Determine release version"
    set_fact:
      _release_version: "{{ ansible_date_time.iso8601_basic_short }}"

  - name: "Determine application release path"
    set_fact:
      _release_path: "{{ justask_base_app_path }}/releases/{{ _release_version }}"

  - name: "Ensure basic directories exist"
    file:
      path: "{{ item }}"
      state: directory
    loop:
      - "{{ justask_base_app_path }}"
      - "{{ justask_base_app_path }}/releases"
      - "{{ _release_path }}"
      - "{{ justask_base_app_path }}/shared/bundle"
      - "{{ justask_base_app_path }}/shared/config"
      - "{{ justask_base_app_path }}/shared/config/initializers"
      - "{{ justask_base_app_path }}/shared/log"
      - "{{ justask_base_app_path }}/shared/public"
      - "{{ justask_base_app_path }}/shared/tmp"

  - name: "Update repo"
    git:
      repo: https://github.com/Retrospring/retrospring.git
      dest: "{{ justask_base_app_path }}/repo"
      bare: yes
      update: yes

  - name: "Create release"
    shell: |-
      git archive {{ rs_version }} | /usr/bin/env tar -x -f - -C {{ _release_path }}
    args:
      chdir: "{{ justask_base_app_path }}/repo"

  - name: "Record REVISION"
    shell: |-
      git rev-parse {{ rs_version }} > {{ _release_path }}/REVISION
    args:
      chdir: "{{ justask_base_app_path }}/repo"

  - name: "Symlink shared files"
    file:
      src: "{{ justask_base_app_path }}/shared/{{ item }}"
      dest: "{{ _release_path }}/{{ item }}"
      state: link
      force: yes
    loop: "{{ justask_shared_files }}"

  - name: "Ensure shared dirs exist"
    file:
      path: "{{ justask_base_app_path }}/shared/{{ item }}"
      state: directory
    loop: "{{ justask_shared_dirs }}"
  - name: "Remove dirs we need to symlink"
    file:
      dest: "{{ _release_path }}/{{ item }}"
      state: absent
    loop: "{{ justask_shared_dirs }}"
  - name: "Symlink shared dirs"
    file:
      src: "{{ justask_base_app_path }}/shared/{{ item }}"
      dest: "{{ _release_path }}/{{ item }}"
      state: link
      force: yes
    loop: "{{ justask_shared_dirs }}"

  - name: "Install the bundle"
    shell: |-
      $SHELL -lc "bundle config build.pg --with-pg-config=/usr/pgsql-10/bin/pg_config"
      $SHELL -lc "bundle config set without 'development test'"
      $SHELL -lc "bundle config set path '{{ justask_base_app_path }}/shared/bundle'"
      $SHELL -lc "bundle install --jobs=3"
    args:
      chdir: "{{ _release_path }}"

  become: true
  become_user: justask
