---
- name: "Create justask user"
  user:
    name: "justask"
    comment: "justask-retrospring user"
    create_home: yes
    state: present

- name: "Figure out which Ruby version to use"
  uri:
    url: "https://raw.githubusercontent.com/Retrospring/retrospring/main/.ruby-version"
    return_content: yes
  register: ruby_version_response
- set_fact:
    ruby_version: "{{ ruby_version_response.content | trim }}"

- name: "Set up Ruby"
  include_role:
    name: rbenv

- name: "Deploy"
  import_tasks: deploy.yml

- name: "Create Puma configuration file"
  copy:
    src: "puma.rb"
    dest: "{{ justask_base_app_path }}/shared/config/puma.rb"
    force: yes

- name: "Create justask SystemD units"
  copy:
    src: "{{ item }}.service"
    dest: "/etc/systemd/system/{{ item }}.service"
    mode: "0644"
  loop:
    - justask-sidekiq

- name: "Reload SystemD"
  systemd:
    daemon_reload: yes

- name: "Restart justask-sidekiq"
  systemd:
    name: "justask-sidekiq"
    enabled: yes
    state: restarted

# no more web on this instance
- name: "Ensure web@01 is disabled"
  systemd:
    name: "justask-web@01"
    enabled: no

- name: "Ensure web@02 is disabled"
  systemd:
    name: "justask-web@02"
    enabled: no
